version: '3.7'
services:
  app:
    image: backendimage
    build: ./backend/target/inventory-management-docker.jar
    ports:
      - "8080:8080"
    depends_on:
      - pdb
    networks:
      - shared-network
  pdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sejal
      - POSTGRES_USER=postgres
      - POSTGRES_DB=inventory_management_pdb
    networks:
      - shared-network
  client:
    image : frontendimage
    build : ./frontend
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - app
    networks:
      - shared-network
networks:
  shared-network:
